### ISSUE TITLE
Como Criar Menu Lateral Apenas Com CSS? Menu totalmente funcional e sem complicações

### ISSUE THREAD

**Issue by andrelinos** [andrelinos/blog#2]
## Veja como é simples!
- Crie um arquivo menu.html
- Crie uma pasta junto a este chamada css.
- Dentro da pasta, crie um arquivo chamado style.css

## Código para dentro do arquivo menu.html

```html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Menu sidebar</title>
  <link rel="stylesheet" type="text/css" href="./css/style.css">
</head>
<body>
  <div id="container">
        <div id="nav-menu">
            <div class="bg"></div>
				<div class="button" tabindex="0">
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				</div>
			<div id="content-menu" tabindex="0">
			<ul>
				<li><a href="#">Página inicial</a></li>
				<li><a href="#">Quem somos?</a></li>
				<li><a href="#">Nossa empresa</a></li>
				<li><a href="#">Nosso portifólio</a></li>
				<li><a href="#">Trabalhe conosco</a></li>
				<li><a href="#">Faça um orçamento</a></li>
				<li><a href="#">Fale conocos</a></li>
				<li><a href="#">Ferramentas</a></li>
				<li><a href="#">Nosso endereço</a></li>
				<li><a href="#">Ajuda</a></li>
			</ul>
			</div>
		</div>
	</div>
</body>
</html>
```

## Conteúdo do arquivo style.css 

```css
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  outline: none;
}

body {
  width: 100%;
  min-height: 100%;
  background: #333;
  background-size: cover;
  font-size: 16px;
  font-family: 'Arial', sans-serif;
  font-weight: 400;
}

a {
	text-decoration: none;
	color: #fff;
}
a:hover {
	text-decoration: underline;
}
ul, li {
	list-style: none;
	line-height: 2;
}
/* Menu */
#nav-menu {
  position: fixed;
  height: 100%;
  width: 100%;
  pointer-events: none;
}

#nav-menu .bg {
  position: absolute;
  top: 70px;
  left: 0;
  width: 100%;
  height: calc(100% - 70px);
  visibility: hidden;
  opacity: 0;
  transition: .3s;
}

#nav-menu:focus-within .bg {
  visibility: visible;
  opacity: 6;
}

#nav-menu * {
  visibility: visible;
}

.button {
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: center;
  border: 0;
  background: transparent;
  border-radius: 0;
  height: 70px;
  width: 30px;
  cursor: pointer;
  margin-left: 26px;
  touch-action: manipulation;
  pointer-events: auto;
  -webkit-tap-highlight-color: rgba(0,0,0,0);
  -webkit-appearance: none;
  z-index: 99;
}

#nav-menu:focus-within .button {
  pointer-events: none;
}

.icon-bar {
  display: block;
  width: 100%;
  height: 3px;
  background: #f5f5f5;
  transition: .3s;
}
.icon-bar + .icon-bar {
  margin-top: 5px;
}

#nav-menu:focus-within .icon-bar:nth-of-type(1) {
  transform: translate3d(0,8px,0) rotate(45deg);
}
#nav-menu:focus-within .icon-bar:nth-of-type(2) {
  opacity: 0;
}
#nav-menu:focus-within .icon-bar:nth-of-type(3) {
  transform: translate3d(0,-8px,0) rotate(-45deg);
}

#content-menu {
  margin-top: 70px;
  padding: 10px;
  width: 90%;
  background: #00BFFF;
  max-width: 300px;
  position: absolute;
  top: 0;
  left: 0;
  height: calc(100% - 70px);
  pointer-events: auto;
  -webkit-tap-highlight-color: rgba(0,0,0,0);
  transform: translateX(-100%);
  transition: transform .3s;
  will-change: transform;
  contain: paint;
  opacity: 0.8;
}
#nav-menu:focus-within #content-menu {
  transform: none;
}
```

Basicamente com este código você já terá seu menu sidebar funcional para seu site.
